-- MEMBER_DB / TB_MEMBER_STATUS_T
-- 회원 상태 정보 테이블

CREATE TABLE TB_MEMBER_STATUS_T (
    MEMBER_ID       BIGINT        NOT NULL,                 -- 내부 식별자 (회원ID)
    MEMBER_STATUS   VARCHAR(20)   NOT NULL,                 -- 회원상태
    ALTER_DT        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 변경일자
    ALTER_MEMO      VARCHAR(255),                            -- 변경사유

    CONSTRAINT PK_TB_MEMBER_STATUS_T
        PRIMARY KEY (MEMBER_ID),

    CONSTRAINT FK_TB_MEMBER_STATUS_T_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES TB_MEMBER_BASIC_M (MEMBER_ID),

    CONSTRAINT CK_TB_MEMBER_STATUS_T_STATUS
        CHECK (MEMBER_STATUS IN ('NORMAL', 'LOCK', 'DORMANT', 'WITHDRAW_REQ', 'WITHDRAW'))
);
