-- MEMBER_DB / TB_MEMBER_VISIT_T
-- 회원 방문 정보(접속 이벤트) 테이블

CREATE TABLE TB_MEMBER_VISIT_T (
    MEMBER_ID     BIGINT        NOT NULL,  -- 내부 식별자 (회원ID)
    VISIT_CD      VARCHAR(20)   NOT NULL,  -- 방문정보(이벤트 코드)
    VISIT_DT      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 방문일자(발생 시각)
    PWD_ERR_CNT   INTEGER       NOT NULL DEFAULT 0, -- 비밀번호 오류 횟수(이벤트 시점)

    CONSTRAINT PK_TB_MEMBER_VISIT_T
        PRIMARY KEY (MEMBER_ID, VISIT_CD, VISIT_DT),

    CONSTRAINT FK_TB_MEMBER_VISIT_T_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES TB_MEMBER_BASIC_M (MEMBER_ID),

    CONSTRAINT CK_TB_MEMBER_VISIT_T_VISIT_CD
        CHECK (VISIT_CD IN ('LOGIN', 'LOGOUT', 'PWD_ERR')),

    CONSTRAINT CK_TB_MEMBER_VISIT_T_PWD_ERR_CNT
        CHECK (PWD_ERR_CNT >= 0)
);