-- RECOM_DB / TB_MEMBER_MY_PERFUME_T
-- 회원별 등록 향수(관심/보유/미관심) 관리 테이블

CREATE TABLE TB_MEMBER_MY_PERFUME_T (
    MEMBER_ID        BIGINT        NOT NULL,  -- member_db 논리 FK
    PERFUME_ID       BIGINT        NOT NULL,  -- perfume_db 논리 FK
    PERFUME_NAME     VARCHAR(200)  NOT NULL,  -- 등록 시점 향수명 스냅샷

    REGISTER_STATUS VARCHAR(20)   NOT NULL,  -- HAVE / HAD / RECOMMENDED / NONE
    PREFERENCE       VARCHAR(20)   NOT NULL,  -- GOOD / BAD / NEUTRAL
    
    REGISTER_REASON  TEXT,                     -- 추가 메모
    REGISTER_DT      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ALTER_DT         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_MEMBER_MY_PERFUME_T
        PRIMARY KEY (MEMBER_ID, PERFUME_ID),

    CONSTRAINT CK_TB_MEMBER_MY_PERFUME_T_OWNERSHIP
        CHECK (OWNERSHIP_STATUS IN ('HAVE', 'HAD', 'RECOMMENDED', 'NONE')),
        
    CONSTRAINT CK_TB_MEMBER_MY_PERFUME_T_PREFERENCE
        CHECK (PREFERENCE IN ('GOOD', 'BAD', 'NEUTRAL'))
);

CREATE INDEX IDX_MY_PERFUME_MEMBER_OWNERSHIP
ON TB_MEMBER_MY_PERFUME_T (MEMBER_ID, OWNERSHIP_STATUS);

CREATE INDEX IDX_MY_PERFUME_MEMBER_PREFERENCE
ON TB_MEMBER_MY_PERFUME_T (MEMBER_ID, PREFERENCE);