-- RECOM_DB / TB_MEMBER_MY_PERFUME_T
-- 회원별 등록 향수(관심/보유/미관심) 관리 테이블

CREATE TABLE TB_MEMBER_MY_PERFUME_T (
    MEMBER_ID        BIGINT        NOT NULL,  -- member_db 논리 FK
    PERFUME_ID       BIGINT        NOT NULL,  -- perfume_db 논리 FK
    PERFUME_NAME     VARCHAR(200)  NOT NULL,  -- 등록 시점 향수명 스냅샷
    PERFUME_STATUS   VARCHAR(20)   NOT NULL,  -- INTEREST / OWNED / NOT_INTEREST
    REGISTER_REASON  TEXT,
    REGISTER_DT      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_MEMBER_MY_PERFUME_T
        PRIMARY KEY (MEMBER_ID, PERFUME_ID),

    CONSTRAINT CK_TB_MEMBER_MY_PERFUME_T_STATUS
        CHECK (PERFUME_STATUS IN ('INTEREST', 'OWNED', 'NOT_INTEREST'))
);

-- 추천/필터 성능용 인덱스
CREATE INDEX IDX_MY_PERFUME_MEMBER_STATUS
ON TB_MEMBER_MY_PERFUME_T (MEMBER_ID, PERFUME_STATUS);