CREATE TABLE TB_PERFUME_OCA_M (
    PERFUME_ID  BIGINT        NOT NULL,
    OCCASION    VARCHAR(50)   NOT NULL,
    VOTE        INTEGER,
    LOAD_DT     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_PERFUME_OCA_M
        PRIMARY KEY (PERFUME_ID, OCCASION),

    CONSTRAINT FK_TB_PERFUME_OCA_M_PERFUME
        FOREIGN KEY (PERFUME_ID)
        REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);