CREATE TABLE TB_PERFUME_ACCORD_R (
    PERFUME_ID BIGINT NOT NULL, -- 향수ID
    ACCORD VARCHAR(100) NOT NULL, -- 어코드명
    RATIO NUMERIC(5, 2), -- 비율
    LOAD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PERFUME_ACCORD_R PRIMARY KEY (PERFUME_ID, ACCORD),
    CONSTRAINT FK_TB_PERFUME_ACCORD_R_PERFUME FOREIGN KEY (PERFUME_ID) REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);