CREATE TABLE TB_PERFUME_GENDER_R (
    PERFUME_ID BIGINT NOT NULL,
    GENDER VARCHAR(20) NOT NULL, -- 'Feminine', 'Masculine', 'Unisex'
    LOAD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PERFUME_GENDER_R PRIMARY KEY (PERFUME_ID),
    CONSTRAINT FK_TB_PERFUME_GENDER_R_PERFUME FOREIGN KEY (PERFUME_ID) REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);