CREATE TABLE TB_PERFUME_ACCORD_M (
    PERFUME_ID  BIGINT        NOT NULL,                 -- 향수ID
    ACCORD      VARCHAR(100)  NOT NULL,                 -- 어코드명
    VOTE        INTEGER,                                -- 투표수
    LOAD_DT     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_PERFUME_ACCORD_M
        PRIMARY KEY (PERFUME_ID, ACCORD),

    CONSTRAINT FK_TB_PERFUME_ACCORD_M_PERFUME
        FOREIGN KEY (PERFUME_ID)
        REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);
