CREATE TABLE TB_PERFUME_SEASON_M (
    PERFUME_ID  BIGINT        NOT NULL,
    SEASON      VARCHAR(20)   NOT NULL,
    VOTE        INTEGER,
    LOAD_DT     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_PERFUME_SEASON_M
        PRIMARY KEY (PERFUME_ID, SEASON),

    CONSTRAINT FK_TB_PERFUME_SEASON_M_PERFUME
        FOREIGN KEY (PERFUME_ID)
        REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);