CREATE TABLE TB_PERFUME_OCA_R (
    PERFUME_ID BIGINT NOT NULL, -- 향수ID
    OCCASION VARCHAR(50) NOT NULL, -- 상황 (Daily, Leisure 등)
    RATIO NUMERIC(5, 2), -- 비율
    LOAD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PERFUME_OCCASION_R PRIMARY KEY (PERFUME_ID, OCCASION),
    CONSTRAINT FK_TB_PERFUME_OCCASION_R_PERFUME FOREIGN KEY (PERFUME_ID) REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);