CREATE TABLE TB_PERFUME_BASIC_M (
    PERFUME_ID      BIGINT          NOT NULL,
    PERFUME_NAME    VARCHAR(200)    NOT NULL,
    PERFUME_BRAND   VARCHAR(100)    NOT NULL,
    RELEASE_YEAR    INTEGER,
    CONCENTRATION   VARCHAR(50),
    PERFUMER        VARCHAR(100),
    IMG_LINK        TEXT,
    LOAD_DT         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PERFUME_BASIC_M PRIMARY KEY (PERFUME_ID)
);

-- PERFUME_NAME + PERFUME_BRAND 조합 중복 방지시
-- CREATE UNIQUE INDEX UX_PERFUME_NAME_BRAND
-- ON TB_PERFUME_BASIC_M (PERFUME_NAME, PERFUME_BRAND);