-- DROP TABLE IF EXISTS TB_PERFUME_NOTES_M;
CREATE TABLE TB_PERFUME_NOTES_M (
    PERFUME_ID  BIGINT        NOT NULL,
    NOTE        VARCHAR(100)  NOT NULL,
    TYPE        VARCHAR(20)   NOT NULL,
    LOAD_DT     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_PERFUME_NOTES_M
        PRIMARY KEY (PERFUME_ID, NOTE, TYPE),

    CONSTRAINT CK_TB_PERFUME_NOTES_M_TYPE
        CHECK (TYPE IN ('TOP', 'MIDDLE', 'BASE')),

    CONSTRAINT FK_TB_PERFUME_NOTES_M_PERFUME
        FOREIGN KEY (PERFUME_ID)
        REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);