-- DROP TABLE IF EXISTS TB_PERFUME_REVIEW_M;
CREATE TABLE TB_PERFUME_REVIEW_M (
    REVIEW_ID BIGINT NOT NULL, -- 숫자만 저장 (예: 60000)
    PERFUME_ID BIGINT NOT NULL, -- 숫자만 저장 (예: 8281)
    CONTENT TEXT NOT NULL, -- 리뷰 본문
    TAGS TEXT, -- (추가됨) 태그 정보
    SOURCE VARCHAR(20) NOT NULL, -- 'Fragrantica' or 'Parfumo'
    LOAD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PERFUME_REVIEW_M PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_TB_PERFUME_REVIEW_M_PERFUME FOREIGN KEY (PERFUME_ID) REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);