CREATE TABLE TB_PERFUME_SEASON_R (
    PERFUME_ID BIGINT NOT NULL, -- 향수ID
    SEASON VARCHAR(50) NOT NULL, -- 계절 (Spring, Summer, Fall, Winter)
    RATIO NUMERIC(5, 2), -- 비율
    LOAD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PERFUME_SEASON_R PRIMARY KEY (PERFUME_ID, SEASON),
    CONSTRAINT FK_TB_PERFUME_SEASON_R_PERFUME FOREIGN KEY (PERFUME_ID) REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);