export const BACKEND_ACCORDS = [
  "Fresh",
  "Citrus",
  "Fruity",
  "Sweet",
  "Floral",
  "Powdery",
  "Creamy",
  "Gourmand",
  "Oriental",
  "Spicy",
  "Animal",
  "Leathery",
  "Smoky",
  "Woody",
  "Resinous",
  "Earthy",
  "Chypre",
  "Fougère",
  "Green",
  "Aquatic",
  "Synthetic",
] as const;

export const DISPLAY_ACCORDS = [
  "Fresh",
  "Citrus",
  "Fruity",
  "Sweet",
  "Floral",
  "Powdery",
  "Creamy",
  "Gourmand",
  "Oriental",
  "Spicy",
  "Animal",
  "Leathery",
  "Smoky",
  "Woody",
  "Resinous",
  "Earthy",
  "Chypre",
  "Fougère",
  "Green",
  "Aquatic",
  "Synthetic",
] as const;

export const ACCORD_COLORS: Record<(typeof BACKEND_ACCORDS)[number], string> = {
  Fresh: "#8FB5FF",
  Citrus: "#E6E04A",
  Fruity: "#F39A4C",
  Sweet: "#F4A3C4",
  Floral: "#F6B3C6",
  Powdery: "#E9CFCF",
  Creamy: "#F1E8D6",
  Gourmand: "#B97A4B",
  Oriental: "#7A3E2F",
  Spicy: "#9E3B32",
  Animal: "#7A5C3E",
  Leathery: "#2E2B28",
  Smoky: "#7B7B7B",
  Woody: "#6B4F2A",
  Resinous: "#4B6F8A",
  Earthy: "#AD868B",
  Chypre: "#3F6F5E",
  "Fougère": "#6F7A4A",
  Green: "#4FA66A",
  Aquatic: "#5FBED7",
  Synthetic: "#7FA1D6",
};
